services:
  - type: web
    name: leadgen-assessment
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: leadgen-assessment-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: BASE_URL
        value: https://leadgen-assessment.onrender.com
      - key: HUBSPOT_API_KEY
        sync: false
      - key: HUBSPOT_SOURCE
        value: leadgen-assessment
      - key: NEXT_PUBLIC_POSTHOG_KEY
        sync: false

databases:
  - name: leadgen-assessment-db
    plan: starter
